site_name: Mad-Pascal
theme: readthedocs
nav:
    - Wprowadzenie: 01-wprowadzenie.md
    - Sposób użycia: 02-sposob-uzycia.md
    - Składnia: 03-skladnia.md
    - Stałe: 04-stale.md
    - Typy: 05-typy.md
    - Instrukcje warunkowe: 06-instrukcje-warunkowe.md
    - Instrukcje interacyjne: 07-instrukcje-iteracyjne.md
    - Procedury, funkcje, modyfikatory: 08-procedury-funkcje.md
    - Moduły: 09-moduly.md
