site_name: Mad-Pascal
site_author: TeBe
site_description: "Mad-Pascal Dokumentacja"
site_keyword: "cross-compiler"

theme:
    name: readthedocs
    highlightjs: true
    hljs_style: dark
    hljs_languages:
        - delphi

nav:
    - Wprowadzenie: wprowadzenie.md
    - Sposób użycia: sposob-uzycia.md
    - Składnia: skladnia.md
    - Stałe: stale.md
    - Typy: typy.md
    - Instrukcje: instrukcje.md
    - Procedury, funkcje, modyfikatory: procedury-funkcje.md
    - Moduły: moduly.md
    - Biblioteki podstawowe: biblioteki-podstawowe.md
    - Przykłady: przyklady.md
    - Projekty: projekty.md
